### ISSUE TITLE
Looks good

### ISSUE THREAD

**Issue by erg-hzhou** [aramsdell/AWSbackups#1]
Check if you receive this testing message - Hui

**Comment by aramsdell** [comment]
Got it!!!!!!

**Comment by erg-hzhou** [comment]
Ok, I am going to invite you to ERG again.

**Comment by pauldzy** [comment]
Is education possibly a process of trading awareness for things of lesser worth? The goose who trades his is soon a pile of feathers.

**Comment by aramsdell** [comment]
![download](https://user-images.githubusercontent.com/2932138/55079910-81c2d000-5073-11e9-8a54-f5b8c9f5ba63.jpg)
